name: slide_action
description: A customizable slide to perform an action widget.
version: 0.0.1
homepage: https://github.com/kay-af/slide-action.git

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0